const express=require('express');
const path=require('path');
const {requireCoreAuth}=require('./security');
const {validateSources}=require('../core/sourceValidation');
const {TelegramAdapter}=require('../adapters/telegramAdapter');
const {EmailAdapter}=require('../adapters/emailAdapter');
const {BucketAdapter}=require('../adapters/bucketAdapter');
const {version}=require('../../package.json');

function reportSubject(report){
  const stamp=report?.generatedAt?new Date(report.generatedAt):new Date();
  const date=new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(stamp);
  return `SUPERVISOR SCB — Reporte ${date}`;
}
function communicationCheckpoint(channel,result,error=null){
  return{channel,ok:!error,result:result||null,error:error?String(error.message||error):null,at:new Date().toISOString()};
}
function dailySubject(report){return `SUPERVISOR SCB — Cierre Gerencial ${report?.date||''}`.trim()}
function createApp({engine,dailyService,dailyV3LiveService,manualSupervisionService,remoteService,databases,config,telegramAdapter,emailAdapter,bucketAdapter}){
  const app=express();app.use(express.json({limit:'1mb'}));
  const auth=requireCoreAuth(process.env);
  const telegram=telegramAdapter||new TelegramAdapter(process.env);
  const email=emailAdapter||new EmailAdapter(process.env);
  const bucket=bucketAdapter||new BucketAdapter(process.env);
  const saveComm=(channel,result,error)=>engine.store.saveCheckpoint(`communication_last_${channel}`,communicationCheckpoint(channel,result,error));
  const getComm=channel=>engine.store.getCheckpoint(`communication_last_${channel}`);
  async function latestOrGenerate(run){let report=await engine.store.getLatestReport();if(run||!report){const out=await engine.run({now:new Date()});report=out.report}if(!report)throw new Error('REPORT_NOT_AVAILABLE');return report}
  async function sendTelegramReport(report){const sent=await telegram.send(report.text);const at=new Date().toISOString();await engine.store.saveReport(report.id||report.reportId||`manual-${Date.now()}`,{...report,telegramSent:true,telegramMessageId:sent.messageId,telegramSentAt:at});await saveComm('telegram',sent);return sent}
  async function sendDailyTelegram(report,chatIdOverride=null){const sent=await telegram.send(report.text,chatIdOverride||null);const at=new Date().toISOString();await engine.store.saveDailyReport(report.date,{...report,telegramSent:true,telegramMessageId:sent.messageId,telegramSentAt:at});await saveComm('telegram',sent);return sent}
  async function sendDailyEmail(report){const sent=await email.send({subject:dailySubject(report),bodyText:report.text,bodyHtml:report.html,operationId:`daily-${report.date}`,source:'supervisor-scb-daily-gerencial'});const at=new Date().toISOString();await engine.store.saveDailyReport(report.date,{...report,emailSent:true,emailLogId:sent.logId,emailMessageId:sent.messageId,emailSentAt:at});await saveComm('email',sent);return sent}
  async function sendEmailReport(report){const sent=await email.send({subject:reportSubject(report),bodyText:report.text,bodyHtml:report.html,operationId:`report-${report.id||report.reportId||report.runId||Date.now()}`,source:'supervisor-scb-report'});const at=new Date().toISOString();await engine.store.saveReport(report.id||report.reportId||`manual-${Date.now()}`,{...report,emailSent:true,emailLogId:sent.logId,emailMessageId:sent.messageId,emailSentAt:at});await saveComm('email',sent);return sent}

  app.get('/',(_q,r)=>r.sendFile(path.join(__dirname,'../../public/index.html')));
  app.get('/reports',(_q,r)=>r.sendFile(path.join(__dirname,'../../public/reports.html')));
  app.get('/api',(_q,r)=>r.json({ok:true,service:'SUPERVISOR SCB V3',version,endpoints:['/health','/api/core/status','/api/core/validate-sources','/api/core/run','/api/integrations/status','/api/integrations/email/validate','/api/integrations/email/test','/api/integrations/telegram/test','/api/integrations/bucket/validate','/api/supervisor/report/generate','/api/supervisor/report','/api/supervisor/report/send/telegram','/api/supervisor/report/send/email','/api/supervisor/report/send/all','/api/supervisor/daily/start','/api/supervisor/daily/process','/api/supervisor/daily/status','/api/supervisor/daily/generate','/api/supervisor/daily','/api/supervisor/daily/send/telegram','/api/supervisor/daily/send/email','/api/supervisor/daily/send/all']}));
  app.get('/health',(_q,r)=>r.json({ok:true,version,databases:databases.ids,sourceReadOnly:true,telegramConfigured:telegram.isConfigured(),emailConfigured:email.isConfigured(),bucketConfigured:bucket.isConfigured(),bucketName:bucket.name||null,openaiConfigured:!!dailyService?.openai?.isConfigured?.(),openaiModel:dailyService?.openai?.model||null}));
  app.get('/api/core/validate-sources',auth,async(_q,r)=>r.json({ok:true,validation:await validateSources(databases)}));
  app.get('/api/core/status',auth,async(_q,r)=>r.json({ok:true,version,latestRun:await engine.store.getLatestRun(),crmInitialSnapshot:await engine.store.getCheckpoint('crm_initial_snapshot_v1')}));
  app.post('/api/core/run',auth,async(q,r)=>{try{const now=q.body?.now?new Date(q.body.now):new Date();r.json({ok:true,result:await engine.run({now})})}catch(e){r.status(500).json({ok:false,error:e.message})}});

  app.get('/api/integrations/status',auth,async(_q,r)=>{try{const [lastTelegram,lastEmail]=await Promise.all([getComm('telegram'),getComm('email')]);r.json({ok:true,telegram:{configured:telegram.isConfigured(),last:lastTelegram},email:{...email.configStatus(),last:lastEmail},bucket:{configured:bucket.isConfigured(),name:bucket.name||null,mode:'validation_only'}})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/integrations/email/validate',auth,async(_q,r)=>{try{const result=await email.validateService();r.json({ok:true,result})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/integrations/email/test',auth,async(_q,r)=>{try{const now=new Date().toISOString();const sent=await email.send({subject:'Prueba SUPERVISOR SCB V3',bodyText:`Prueba de email SUPERVISOR SCB V3\n\nFecha: ${now}\nEstado: OK`,operationId:`email-test-${Date.now()}`,source:'supervisor-scb-test'});await saveComm('email',sent);r.json({ok:true,sent})}catch(e){await saveComm('email',null,e).catch(()=>{});r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/integrations/telegram/test',auth,async(_q,r)=>{try{const sent=await telegram.send(`SUPERVISOR SCB V3 — Prueba Telegram\n${new Date().toISOString()}\nEstado: OK`);await saveComm('telegram',sent);r.json({ok:true,sent})}catch(e){await saveComm('telegram',null,e).catch(()=>{});r.status(500).json({ok:false,error:e.message})}});
  app.get('/api/integrations/telegram/chats',auth,async(_q,r)=>{try{r.json({ok:true,chats:await telegram.listRecentChats()})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/integrations/telegram/test-chat',auth,async(q,r)=>{try{const chatId=String(q.body?.chatId||'').trim();if(!chatId)throw new Error('TELEGRAM_CHAT_ID_REQUIRED');r.json({ok:true,sent:await telegram.testChat(chatId,q.body?.label||'SUPERVISOR SCB')})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/integrations/bucket/validate',auth,async(_q,r)=>{try{r.json({ok:true,result:await bucket.validate()})}catch(e){r.status(500).json({ok:false,error:e.message})}});

  app.post('/api/supervisor/report/generate',auth,async(q,r)=>{try{const now=q.body?.now?new Date(q.body.now):new Date();const out=await engine.run({now});r.json({ok:true,report:out.report,result:{runId:out.runId||out.report?.runId,processedConversations:out.processedConversations,processedDeals:out.processedDeals,crmMode:out.crmMode}})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.get('/api/supervisor/report',auth,async(_q,r)=>r.json({ok:true,report:await engine.store.getLatestReport()}));
  app.post('/api/supervisor/report/send/telegram',auth,async(q,r)=>{try{const report=await latestOrGenerate(q.body?.run===true);r.json({ok:true,sent:await sendTelegramReport(report)})}catch(e){await saveComm('telegram',null,e).catch(()=>{});r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/report/send/email',auth,async(q,r)=>{try{const report=await latestOrGenerate(q.body?.run===true);r.json({ok:true,sent:await sendEmailReport(report)})}catch(e){await saveComm('email',null,e).catch(()=>{});r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/report/send/all',auth,async(q,r)=>{try{const report=await latestOrGenerate(q.body?.run===true);const result={telegram:null,email:null};const errors=[];try{result.telegram=await sendTelegramReport(report)}catch(e){errors.push({channel:'telegram',error:e.message});await saveComm('telegram',null,e).catch(()=>{})}try{result.email=await sendEmailReport(report)}catch(e){errors.push({channel:'email',error:e.message});await saveComm('email',null,e).catch(()=>{})}const ok=errors.length===0;r.status(ok?200:207).json({ok,result,errors})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/report/send',auth,async(q,r)=>{try{const report=await latestOrGenerate(q.body?.run===true);r.json({ok:true,sent:await sendTelegramReport(report)})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/daily/start',auth,async(q,r)=>{try{if(!dailyService)throw new Error('DAILY_SERVICE_NOT_AVAILABLE');const date=String(q.body?.date||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('DAILY_DATE_REQUIRED');const result=await dailyService.start({date,startHour:q.body?.startHour??9,endHour:q.body?.endHour??17,lateMinutes:q.body?.lateMinutes??30,limit:q.body?.limit??500});r.json({ok:true,...result})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/daily/process',auth,async(q,r)=>{try{if(!dailyService)throw new Error('DAILY_SERVICE_NOT_AVAILABLE');const jobId=String(q.body?.jobId||'').trim();if(!jobId)throw new Error('DAILY_JOB_ID_REQUIRED');const result=await dailyService.process({jobId,batchSize:q.body?.batchSize??5});r.json({ok:true,...result})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/daily/status',auth,async(q,r)=>{try{const jobId=String(q.body?.jobId||'').trim();if(!jobId)throw new Error('DAILY_JOB_ID_REQUIRED');const job=await engine.store.getDailyJob(jobId);if(!job)throw new Error('DAILY_JOB_NOT_FOUND');r.json({ok:true,job,report:job.status==='complete'?await engine.store.getDailyReport(job.date):null})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/daily/generate',auth,async(q,r)=>{try{if(!dailyService)throw new Error('DAILY_SERVICE_NOT_AVAILABLE');const date=String(q.body?.date||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('DAILY_DATE_REQUIRED');const report=await dailyService.generate({date});r.json({ok:true,report})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.get('/api/supervisor/daily',auth,async(q,r)=>{try{const report=q.query.date?await engine.store.getDailyReport(q.query.date):await engine.store.getLatestDailyReport();r.json({ok:true,report})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/daily/send/telegram',auth,async(q,r)=>{try{let report=q.body?.date?await engine.store.getDailyReport(q.body.date):await engine.store.getLatestDailyReport();if(!report&&q.body?.generate===true)report=await dailyService.generate({date:q.body?.date||undefined});if(!report)throw new Error('DAILY_REPORT_NOT_AVAILABLE');r.json({ok:true,sent:await sendDailyTelegram(report)})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/daily/send/general-group',auth,async(q,r)=>{try{
    let report=q.body?.date?await engine.store.getDailyReport(q.body.date):await engine.store.getLatestDailyReport();
    if(!report&&q.body?.generate===true)report=await dailyService.generate({date:q.body?.date||undefined});
    if(!report)throw new Error('DAILY_REPORT_NOT_AVAILABLE');
    if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');
    const setup=await remoteService.getNetworkSetup();
    const chatId=String(q.body?.chatId||setup.settings?.weekday?.generalChatId||'').trim();
    if(!chatId)throw new Error('GENERAL_TELEGRAM_CHAT_REQUIRED');
    r.json({ok:true,chatId,sent:await sendDailyTelegram(report,chatId)});
  }catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/daily/send/email',auth,async(q,r)=>{try{let report=q.body?.date?await engine.store.getDailyReport(q.body.date):await engine.store.getLatestDailyReport();if(!report&&q.body?.generate===true)report=await dailyService.generate({date:q.body?.date||undefined});if(!report)throw new Error('DAILY_REPORT_NOT_AVAILABLE');r.json({ok:true,sent:await sendDailyEmail(report)})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/daily/send/all',auth,async(q,r)=>{try{let report=q.body?.date?await engine.store.getDailyReport(q.body.date):await engine.store.getLatestDailyReport();if(!report&&q.body?.generate===true)report=await dailyService.generate({date:q.body?.date||undefined});if(!report)throw new Error('DAILY_REPORT_NOT_AVAILABLE');const result={telegram:null,email:null},errors=[];try{result.telegram=await sendDailyTelegram(report)}catch(e){errors.push({channel:'telegram',error:e.message})}try{result.email=await sendDailyEmail(report)}catch(e){errors.push({channel:'email',error:e.message})}r.status(errors.length?207:200).json({ok:errors.length===0,result,errors})}catch(e){r.status(500).json({ok:false,error:e.message})}});

  app.get('/api/supervisor/network/setup',auth,async(_q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');r.json({ok:true,...await remoteService.getNetworkSetup()})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/network/setup',auth,async(q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');r.json({ok:true,...await remoteService.saveNetworkSetup(q.body||{})})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/network/test-seller',auth,async(q,r)=>{try{const sellerId=String(q.body?.sellerId||'').trim();if(!sellerId)throw new Error('SELLER_ID_REQUIRED');const core=await engine.run({now:new Date()});r.json({ok:true,core:{processedConversations:core.processedConversations,processedDeals:core.processedDeals},result:await remoteService.testSellerGroup(sellerId,{send:q.body?.send===true,dateOverride:q.body?.date||null})})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/network/test-general',auth,async(q,r)=>{try{r.json({ok:true,result:await remoteService.testGeneral({send:q.body?.send===true,chatIdOverride:q.body?.chatId||null})})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/network/test-weekend',auth,async(q,r)=>{try{r.json({ok:true,result:await remoteService.testWeekend({send:q.body?.send===true,chatIdOverride:q.body?.chatId||null})})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.get('/api/supervisor/remote/sellers',auth,async(_q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');r.json({ok:true,sellers:await remoteService.listSellerOptions()})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.get('/api/supervisor/remote/configs',auth,async(_q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');r.json({ok:true,supervisors:await remoteService.listSupervisors()})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/remote/config',auth,async(q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');r.json({ok:true,supervisor:await remoteService.saveSupervisor(q.body||{})})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/remote/action',auth,async(q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');r.json({ok:true,action:await remoteService.createAction(q.body||{})})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/remote/verify',auth,async(q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');r.json({ok:true,actions:await remoteService.verifyPending({limit:q.body?.limit||100})})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/remote/run',auth,async(q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');const supervisorId=String(q.body?.supervisorId||'').trim();if(!supervisorId)throw new Error('REMOTE_SUPERVISOR_ID_REQUIRED');r.json({ok:true,result:await remoteService.runSupervisor(supervisorId,{now:q.body?.now?new Date(q.body.now):new Date(),send:q.body?.send!==false,force:q.body?.force===true})})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/remote/tick',auth,async(q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');const now=q.body?.now?new Date(q.body.now):new Date();r.json({ok:true,...await remoteService.automationTick({engine,now,send:q.body?.send!==false,force:q.body?.force===true,source:q.body?.source==='scheduler'?'scheduler':'manual'})})}catch(e){r.status(500).json({ok:false,error:e.message,health:remoteService?await remoteService.getAutomationHealth().catch(()=>null):null})}});
  app.get('/api/supervisor/automation/health',auth,async(_q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');r.json({ok:true,health:await remoteService.getAutomationHealth()})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/automation/pause',auth,async(q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');r.json({ok:true,health:await remoteService.pauseAutomation(q.body?.reason||'MANUAL_PAUSE')})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/automation/resume',auth,async(_q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');r.json({ok:true,health:await remoteService.resumeAutomation()})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  function manualGuideReportKey(date,cutoff=17){return `${date}__cutoff_${Number(cutoff)}__guide_v1`}
  app.post('/api/supervisor/manual/start',auth,async(q,r)=>{try{
    const date=String(q.body?.date||'').trim(),cutoff=Number(q.body?.cutoff||17);
    if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('DAILY_DATE_REQUIRED');
    const reportKey=manualGuideReportKey(date,cutoff);
    const cached=await engine.store.getDailyReport(reportKey);
    if(cached&&Array.isArray(cached.rows)&&q.body?.refresh!==true)return r.json({ok:true,cached:true,reportKey,report:cached});
    const result=await dailyService.start({date,startHour:9,endHour:cutoff,lateMinutes:30,limit:500,forceAi:false,reportKey,reviewScope:'guide_v1'});
    r.json({ok:true,cached:false,reportKey,...result});
  }catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/manual/process',auth,async(q,r)=>{try{
    const jobId=String(q.body?.jobId||'').trim();if(!jobId)throw new Error('DAILY_JOB_ID_REQUIRED');
    const result=await dailyService.process({jobId,batchSize:Math.max(1,Math.min(3,Number(q.body?.batchSize||2)))});
    r.json({ok:true,...result});
  }catch(e){r.status(500).json({ok:false,error:e.message})}});
  async function sellerChatId(sellerKey){const setup=await remoteService.getNetworkSetup();const g=(setup.sellerGroups||[]).find(x=>String(x.sellerId||x.sellers?.[0]||'').toLowerCase()===String(sellerKey||'').toLowerCase());return g?.telegramChatId||null}
  async function generalChatId(){const setup=await remoteService.getNetworkSetup();return setup.settings?.weekday?.generalChatId||setup.settings?.weekend?.chatId||null}
  app.post('/api/supervisor/manual/live',auth,async(q,r)=>{try{const report=await manualSupervisionService.liveSeller({date:q.body?.date,cutoff:Number(q.body?.cutoff||17),sellerKey:q.body?.sellerKey,sellerLabel:q.body?.sellerLabel,forceAi:q.body?.forceAi===true});let sent=null;if(q.body?.send===true){const chatId=await sellerChatId(q.body?.sellerKey);if(!chatId)throw new Error('SELLER_TELEGRAM_NOT_CONFIGURED');sent=await telegram.send(report.text,chatId)}r.json({ok:true,report,sent})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/manual/super',auth,async(q,r)=>{try{const report=await manualSupervisionService.superSupervisor({date:q.body?.date,cutoff:Number(q.body?.cutoff||10),forceAi:q.body?.forceAi===true});let sent=null;if(q.body?.send===true){const chatId=await generalChatId();if(!chatId)throw new Error('GENERAL_TELEGRAM_NOT_CONFIGURED');sent=await telegram.send(report.text,chatId)}r.json({ok:true,report,sent})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/manual/close',auth,async(q,r)=>{try{const report=await manualSupervisionService.closing({date:q.body?.date,forceAi:q.body?.forceAi===true});let sent=null;if(q.body?.send===true){const chatId=await generalChatId();if(!chatId)throw new Error('GENERAL_TELEGRAM_NOT_CONFIGURED');sent=await telegram.send(report.text,chatId)}r.json({ok:true,report,sent})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/daily-v3-live/generate',auth,async(q,r)=>{try{if(!dailyV3LiveService)throw new Error('DAILY_V3_LIVE_NOT_AVAILABLE');const report=await dailyV3LiveService.generateSeller({date:String(q.body?.date||''),sellerKey:String(q.body?.sellerKey||''),sellerLabel:q.body?.sellerLabel||null,force:q.body?.force===true});r.json({ok:true,report})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.post('/api/supervisor/daily-v3-live/compare',auth,async(q,r)=>{try{if(!dailyV3LiveService)throw new Error('DAILY_V3_LIVE_NOT_AVAILABLE');const report=await dailyV3LiveService.compare({dateA:String(q.body?.dateA||''),dateB:String(q.body?.dateB||''),sellerKey:String(q.body?.sellerKey||''),sellerLabel:q.body?.sellerLabel||null,force:q.body?.force===true});r.json({ok:true,report})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.get('/api/supervisor/archive/reports',auth,async(q,r)=>{try{r.json({ok:true,reports:await engine.store.listLiveDailyReports(q.query?.limit||200,q.query?.date||null)})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.get('/api/supervisor/archive/incidents',auth,async(q,r)=>{try{r.json({ok:true,incidents:await engine.store.listCriticalIncidents(q.query?.limit||200,q.query?.status||null)})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.get('/api/supervisor/remote/report',auth,async(q,r)=>{try{const supervisorId=String(q.query?.supervisorId||'').trim();if(!supervisorId)throw new Error('REMOTE_SUPERVISOR_ID_REQUIRED');r.json({ok:true,report:await engine.store.getLatestRemoteReport(supervisorId)})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  app.get('/api/supervisor/remote/compliance',auth,async(q,r)=>{try{if(!remoteService)throw new Error('REMOTE_SUPERVISOR_NOT_AVAILABLE');const seller=String(q.query?.seller||'').trim();if(!seller)throw new Error('SELLER_REQUIRED');r.json({ok:true,compliance:await remoteService.sellerCompliance(seller)})}catch(e){r.status(500).json({ok:false,error:e.message})}});
  return app;
}
module.exports={createApp,reportSubject};
