class SupervisorStore{constructor(db){this.db=db;this.c={conversations:'supervisor_v3_conversation_state',deals:'supervisor_v3_deal_state',hunter:'supervisor_v3_hunter_event_state',checkpoints:'supervisor_v3_checkpoints',runs:'supervisor_v3_runs',events:'supervisor_v3_events',reports:'supervisor_v3_reports',dailyReports:'supervisor_v3_daily_reports'}}
async getCheckpoint(id){const d=await this.db.collection(this.c.checkpoints).doc(id).get();return d.exists?d.data():null}async saveCheckpoint(id,data){await this.db.collection(this.c.checkpoints).doc(id).set({...data,updatedAt:new Date().toISOString()},{merge:true})}
async getConversationState(id){const d=await this.db.collection(this.c.conversations).doc(String(id)).get();return d.exists?{id:d.id,...d.data()}:null}async saveConversationState(id,data){await this.db.collection(this.c.conversations).doc(String(id)).set({...data,updatedAt:new Date().toISOString()},{merge:true})}
async listWaiting(limit=500){const s=await this.db.collection(this.c.conversations).where('currentWaiting','==',true).limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}))}async listPending(limit=500){const rows=await this.listWaiting(limit);return rows.filter(x=>x.metrics?.pendingAssignment)}async listConversationStates(limit=5000){const s=await this.db.collection(this.c.conversations).limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}))}
async getDealState(id){const d=await this.db.collection(this.c.deals).doc(String(id)).get();return d.exists?{id:d.id,...d.data()}:null}async saveDealState(id,data){await this.db.collection(this.c.deals).doc(String(id)).set({...data,updatedAt:new Date().toISOString()},{merge:true})}async listTrackedDeals(limit=10000){const s=await this.db.collection(this.c.deals).where('followUp.tracked','==',true).limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}))}async listActiveDeals(limit=20000){const s=await this.db.collection(this.c.deals).where('portfolio.active','==',true).limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}))}async listAllDeals(limit=20000){const s=await this.db.collection(this.c.deals).limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}))}async setDealPortfolioBatch(rows=[]){for(let i=0;i<rows.length;i+=400){const batch=this.db.batch();for(const r of rows.slice(i,i+400)){const ref=this.db.collection(this.c.deals).doc(String(r.id));batch.set(ref,{portfolio:r.portfolio,updatedAt:new Date().toISOString()},{merge:true})}await batch.commit()}}
async getHunterState(id){const d=await this.db.collection(this.c.hunter).doc(String(id)).get();return d.exists?d.data():null}async saveHunterState(id,data){await this.db.collection(this.c.hunter).doc(String(id)).set({...data,updatedAt:new Date().toISOString()},{merge:true})}async listHunterDay(day,limit=10000){const s=await this.db.collection(this.c.hunter).where('day','==',day).limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}))}
async listEventsRange(from,to,limit=1000){const s=await this.db.collection(this.c.events).where('occurredAt','>=',from).where('occurredAt','<=',to).limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}))}
async saveEvent(event){const id=`${event.type}__${event.dealId}__${event.currentStage}`;const ref=this.db.collection(this.c.events).doc(id);const d=await ref.get();if(d.exists)return false;await ref.set({...event,id,createdAt:new Date().toISOString()});return true}async listEventsSince(since,limit=1000){const s=await this.db.collection(this.c.events).where('occurredAt','>=',since).limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}))}
async startRun(id,data){await this.db.collection(this.c.runs).doc(id).set({...data,status:'RUNNING',startedAt:new Date().toISOString()})}async finishRun(id,data){await this.db.collection(this.c.runs).doc(id).set({...data,status:'COMPLETE',finishedAt:new Date().toISOString()},{merge:true})}async getLatestRun(){const s=await this.db.collection(this.c.runs).orderBy('startedAt','desc').limit(1).get();return s.empty?null:{id:s.docs[0].id,...s.docs[0].data()}}
async saveReport(id,data){await this.db.collection(this.c.reports).doc(id).set({...data,updatedAt:new Date().toISOString()},{merge:true})}async getLatestReport(){const s=await this.db.collection(this.c.reports).orderBy('generatedAt','desc').limit(1).get();return s.empty?null:{id:s.docs[0].id,...s.docs[0].data()}}
async saveDailyReport(date,data){await this.db.collection(this.c.dailyReports).doc(String(date)).set({...data,updatedAt:new Date().toISOString()},{merge:true})}async getDailyReport(date){const d=await this.db.collection(this.c.dailyReports).doc(String(date)).get();return d.exists?{id:d.id,...d.data()}:null}async getLatestDailyReport(){const s=await this.db.collection(this.c.dailyReports).orderBy('generatedAt','desc').limit(1).get();return s.empty?null:{id:s.docs[0].id,...s.docs[0].data()}}
}
module.exports={SupervisorStore};
