const {hubUrl}=require('./dailyGerencial');
const {daysOverdue}=require('./time');

function norm(v){return String(v||'').trim().toLowerCase()}
function sellerMatch(r,key){return norm(r?.seller||r?.owner)===norm(key)}
function pct(n,d){return d?Math.round(n/d*100):0}
function product(row){const ai=row.ai||{};return{defined:ai.product_defined===true,name:String(ai.product_name||'').trim(),source:String(ai.product_source||'NO_CLARO').toUpperCase(),sellerDiscovered:ai.seller_discovered_product===true}}
function profile(row){return String(row?.ai?.customer_profile_type||row?.ai?.customer_profile_guess||'DESCONOCIDO').toUpperCase()}
function checklist(row){const a=row.ai||{},g=a.guide_checklist||{};return{business:g.understood_business===true||a.did_ask_business_context===true,experience:g.knows_import_experience===true||a.did_ask_import_experience===true,supplier:g.knows_supplier===true,scb:g.explained_scb_value===true||a.scb_value_explained===true,recommendation:g.gave_useful_recommendation===true||a.useful_recommendation===true,next:g.left_concrete_next_step===true||a.concrete_next_step===true}}
function needsCorrection(row){const c=checklist(row);return !!(row.noHumanResponse||row.botOnly||row.lateCount>0||row.operationalWithoutDiscovery||row.unexploredPotential||row.needsReviewByAi||row.ai?.grave_failure===true||(!c.business&&row.inboundCount>0)||(!c.next&&row.humanResponded&&row.inboundCount>0))}
function severity(row){const l=String(row?.ai?.grave_failure_level||'NONE').toUpperCase();if(l==='HIPER_GRAVE')return'HIPER_GRAVE';if(l==='GRAVE'||row.noHumanResponse)return'GRAVE';return needsCorrection(row)?'A_CORREGIR':'OK'}
function caseReason(row){const a=row.ai||{};return String(a.grave_failure_reason||a.sales_coaching||a.summary||a.bad_points?.[0]|| (row.noHumanResponse?'Sin respuesta humana.':row.operationalWithoutDiscovery?'Respondió sin suficiente indagación comercial.':row.unexploredPotential?'Potencial comercial no explorado.':row.lateCount>0?`Respuesta tardía (${row.maxHumanResponseMinutes||0} min).`:'Revisar gestión comercial.')).trim()}
function expected(row){const a=row.ai||{},p=product(row),c=checklist(row),parts=[];if(!p.defined)parts.push('descubrir qué producto quiere traer');if(!c.business)parts.push('entender el negocio/canal de venta');if(!c.experience)parts.push('saber si ya importó');if(!c.supplier)parts.push('confirmar proveedor');if(!c.scb)parts.push('explicar valor SCB según perfil');if(!c.recommendation)parts.push('dar una recomendación útil');if(!c.next)parts.push('dejar próximo paso concreto');return parts.slice(0,4).join(', ')||String(a.next_best_reply||'Mantener seguimiento comercial concreto')}
function rowCase(row){const p=product(row);return{conversationId:row.conversationId,contactName:row.contactName||'Sin nombre',seller:row.seller||row.owner||'',product:p,profile:profile(row),severity:severity(row),needsCorrection:needsCorrection(row),reason:caseReason(row),expected:expected(row),hubUrl:row.hubUrl||hubUrl(row.conversationId),lastClientText:row.lastClientText||'',lastHumanText:row.lastHumanText||'',lateMinutes:row.maxHumanResponseMinutes||0,checklist:checklist(row),opportunity:p.defined===true}}
function metrics(rows){const clients=rows.filter(x=>x.inboundCount>0),cases=clients.map(rowCase);return{clients:clients.length,responded:clients.filter(x=>x.humanResponded).length,noResponse:clients.filter(x=>x.noHumanResponse).length,late:clients.filter(x=>x.lateCount>0).length,good:clients.filter(x=>x.goodCommercialResponse).length,toCorrect:cases.filter(x=>x.needsCorrection).length,opportunities:cases.filter(x=>x.opportunity).length,grave:cases.filter(x=>x.severity==='GRAVE').length,hyperGrave:cases.filter(x=>x.severity==='HIPER_GRAVE').length,goodPct:pct(clients.filter(x=>x.goodCommercialResponse).length,clients.length),correctionPct:pct(cases.filter(x=>x.needsCorrection).length,clients.length)}}
function liveText({date,cutoff,label,rows,trend='BASELINE',correctionStatuses={}}){const m=metrics(rows),cases=rows.filter(x=>x.inboundCount>0).map(rowCase).filter(x=>x.needsCorrection);const L=[`📊 SUPERVISOR EN VIVO — ${label}`,`${date} · corte ${cutoff}:00 · acumulado desde 09:00`,'',`Está trabajando: ${m.responded>0?'SÍ':'NO'} · Tendencia: ${trend}`,`Clientes: ${m.clients} · Respondidos: ${m.responded} · Tarde: ${m.late}`,`Bien trabajados: ${m.good} · A corregir: ${m.toCorrect} · Oportunidades: ${m.opportunities}`,'','CLIENTES A CORREGIR'];if(!cases.length)L.push('Sin casos a corregir.');cases.forEach((c,i)=>{const st=correctionStatuses[c.conversationId]||'PENDIENTE';L.push('',`${i+1}. ${c.contactName} — ${st}${c.severity==='HIPER_GRAVE'?' 🚨':c.severity==='GRAVE'?' 🔴':''}`,`Producto: ${c.product.defined?c.product.name||'Producto identificado':'NO IDENTIFICADO'}`,`Producto: ${c.product.source==='VENDEDOR_DESCUBRIO'?'lo descubrió el vendedor':c.product.source==='CLIENTE'?'ya lo indicó el cliente':'todavía no claro'}`,`Perfil: ${c.profile}`,`Problema: ${c.reason}`,`Qué corregir: ${c.expected}`,`HUB: ${c.hubUrl}`)});return L.join('\n')}
function trendFrom(prev,current){if(!prev)return'BASELINE';const a=prev.metrics||{},b=current;const delta=(Number(b.goodPct||0)-Number(a.goodPct||0))-(Number(b.correctionPct||0)-Number(a.correctionPct||0));return delta>=10?'MEJORANDO':delta<=-10?'EMPEORANDO':'ESTABLE'}
function superText({date,cutoff,rows}){const cases=rows.filter(x=>x.inboundCount>0).map(rowCase),opps=cases.filter(x=>x.opportunity),bad=cases.filter(x=>['GRAVE','HIPER_GRAVE'].includes(x.severity));const L=[`🚨 SUPER SUPERVISOR — ${cutoff}:00`,`Fecha ${date}`,'',`Oportunidades con producto definido: ${opps.length}`,`Fallos graves: ${bad.filter(x=>x.severity==='GRAVE').length}`,`Fallos HIPER GRAVES: ${bad.filter(x=>x.severity==='HIPER_GRAVE').length}`,'','🔥 OPORTUNIDADES QUE NO SE PUEDEN PERDER'];if(!opps.length)L.push('Sin oportunidades concretas detectadas.');opps.slice(0,30).forEach((c,i)=>L.push('',`${i+1}. ${c.contactName} — ${c.seller}`,`Producto: ${c.product.name||'Producto identificado'}`,`Perfil: ${c.profile}`,`Gestión: ${c.needsCorrection?'REQUIERE ACCIÓN':'BIEN TRABAJADA'}`,c.needsCorrection?`Falla: ${c.reason}`:'Sin falla grave detectada.',`HUB: ${c.hubUrl}`));L.push('','🚨 FALLOS GRAVES / HIPER GRAVES');if(!bad.length)L.push('Sin fallos graves detectados.');bad.slice(0,30).forEach((c,i)=>L.push('',`${i+1}. ${c.severity} — ${c.contactName} — ${c.seller}`,`Producto: ${c.product.defined?c.product.name||'identificado':'no identificado'}`,`Perfil: ${c.profile}`,`Qué pasó: ${c.reason}`,`Qué debería hacer: ${c.expected}`,`HUB: ${c.hubUrl}`));return L.join('\n')}
function closeText({date,base,rows,dealStates=[]}){const cases=rows.filter(x=>x.inboundCount>0).map(rowCase),opps=cases.filter(x=>x.opportunity);const bySeller=new Map();for(const c of cases){const k=c.seller||'No detectado',x=bySeller.get(k)||{seller:k,clients:0,opps:0,toCorrect:0,grave:0};x.clients++;if(c.opportunity)x.opps++;if(c.needsCorrection)x.toCorrect++;if(['GRAVE','HIPER_GRAVE'].includes(c.severity))x.grave++;bySeller.set(k,x)}const active=dealStates.filter(d=>d.portfolio?.active===true),overdue=active.filter(d=>d.portfolio?.overdue===true),red=overdue.filter(d=>{const due=d.portfolio?.dueDate||d.snapshot?.dueDate;return due&&daysOverdue(due,new Date(`${date}T23:59:59-03:00`))>=7});const L=[`📊 CIERRE DIARIO GERENCIAL — ${date}`,'09:00–17:00','',`Clientes del día: ${cases.length}`,`Oportunidades con producto definido: ${opps.length}`,`Casos a corregir: ${cases.filter(x=>x.needsCorrection).length}`,`Fallos graves/hiper graves: ${cases.filter(x=>['GRAVE','HIPER_GRAVE'].includes(x.severity)).length}`,'','🔴 VENCIDOS — PRIORIDAD GERENCIAL',`Tratos activos: ${active.length}`,`Vencidos: ${overdue.length}`,`Con +7 días: ${red.length}`,'','🔥 OPORTUNIDADES DEL DÍA'];if(!opps.length)L.push('Sin oportunidades concretas detectadas.');opps.slice(0,40).forEach((c,i)=>L.push('',`${i+1}. ${c.contactName} — ${c.seller}`,`Producto: ${c.product.name||'Producto identificado'}`,`Perfil: ${c.profile}`,`Desarrollo: ${c.needsCorrection?'A DESARROLLAR':'BIEN DESARROLLADA'}`,c.needsCorrection?`Qué falta: ${c.expected}`:'',`HUB: ${c.hubUrl}`));L.push('','📋 RESUMEN POR VENDEDOR');[...bySeller.values()].sort((a,b)=>b.toCorrect-a.toCorrect).forEach(x=>L.push(`• ${x.seller}: clientes ${x.clients} · oportunidades ${x.opps} · a corregir ${x.toCorrect} · graves ${x.grave}`));return L.join('\n')}

class ManualSupervisionService{
  constructor({dailyService,store}){this.dailyService=dailyService;this.store=store}
  async base(date,cutoff=17,forceAi=true){return this.dailyService.generate({date,endHour:Number(cutoff),forceAi,reportKey:`${date}__cutoff_${cutoff}__guide_v1`,reviewScope:'guide_v1'})}
  async liveSeller({date,cutoff=17,sellerKey,sellerLabel,forceAi=true}){const base=await this.base(date,cutoff,forceAi),rows=(base.rows||[]).filter(r=>sellerMatch(r,sellerKey));const previous=(await this.store.listLiveDailyReports(300,date)).find(r=>r.reportType==='supervisor_live_operational'&&norm(r.sellerKey)===norm(sellerKey)&&Number(r.cutoff||0)<Number(cutoff));const ms=metrics(rows),trend=trendFrom(previous,ms);const observations=await this.store.listLiveDailyObservationsForSellers([sellerKey],2000);const statuses={};for(const o of observations)if(String(o.sourceDate||'')===String(date)&&o.conversationId)statuses[o.conversationId]=o.status||'PENDIENTE';const report={id:`manual_live__${date}__${cutoff}__${Buffer.from(norm(sellerKey)).toString('base64url').slice(0,80)}`,reportType:'supervisor_live_operational',date,cutoff:Number(cutoff),sellerKey:norm(sellerKey),sellerLabel,generatedAt:new Date().toISOString(),metrics:ms,cases:rows.filter(x=>x.inboundCount>0).map(rowCase),trend,text:liveText({date,cutoff,label:sellerLabel||sellerKey,rows,trend,correctionStatuses:statuses})};await this.store.saveLiveDailyReport(report.id,report);return report}
  async superSupervisor({date,cutoff=10,forceAi=true}){const base=await this.base(date,cutoff,forceAi),rows=base.rows||[];const report={id:`super_supervisor__${date}__${cutoff}`,reportType:'super_supervisor',date,cutoff:Number(cutoff),generatedAt:new Date().toISOString(),metrics:metrics(rows),text:superText({date,cutoff,rows})};await this.store.saveLiveDailyReport(report.id,report);return report}
  async closing({date,forceAi=true}){const base=await this.base(date,17,forceAi),dealStates=await this.store.listAllDeals(20000),rows=base.rows||[];const report={id:`gerencial_close__${date}`,reportType:'gerencial_close',date,cutoff:17,generatedAt:new Date().toISOString(),metrics:metrics(rows),text:closeText({date,base,rows,dealStates})};await this.store.saveLiveDailyReport(report.id,report);return report}
}
module.exports={ManualSupervisionService,rowCase,metrics,needsCorrection,severity,product,profile,checklist,liveText,superText,closeText};
